/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

/**
 *
 * @author Muhtasim
 */
public class Calculator2 extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        put1 = new javax.swing.JButton();
        put2 = new javax.swing.JButton();
        put3 = new javax.swing.JButton();
        put4 = new javax.swing.JButton();
        put5 = new javax.swing.JButton();
        put6 = new javax.swing.JButton();
        put7 = new javax.swing.JButton();
        put8 = new javax.swing.JButton();
        put9 = new javax.swing.JButton();
        put0 = new javax.swing.JButton();
        putDecimal = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        div = new javax.swing.JButton();
        add = new javax.swing.JButton();
        Sine = new javax.swing.JButton();
        Cosine = new javax.swing.JButton();
        Tangent = new javax.swing.JButton();
        BackSpace = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        openBracket = new javax.swing.JButton();
        closeBracket = new javax.swing.JButton();
        Screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        put1.setText("1");
        put1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put1ActionPerformed(evt);
            }
        });

        put2.setText("2");
        put2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put2ActionPerformed(evt);
            }
        });

        put3.setText("3");
        put3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put3ActionPerformed(evt);
            }
        });

        put4.setText("4");
        put4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put4ActionPerformed(evt);
            }
        });

        put5.setText("5");
        put5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put5ActionPerformed(evt);
            }
        });

        put6.setText("6");
        put6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put6ActionPerformed(evt);
            }
        });

        put7.setText("7");
        put7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put7ActionPerformed(evt);
            }
        });

        put8.setText("8");
        put8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put8ActionPerformed(evt);
            }
        });

        put9.setText("9");
        put9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put9ActionPerformed(evt);
            }
        });

        put0.setText("0");
        put0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                put0ActionPerformed(evt);
            }
        });

        putDecimal.setText(".");
        putDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putDecimalActionPerformed(evt);
            }
        });

        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });

        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        mul.setText("X");
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        add.setText("+");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        Sine.setText("Sin");
        Sine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SineActionPerformed(evt);
            }
        });

        Cosine.setText("Cos");
        Cosine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosineActionPerformed(evt);
            }
        });

        Tangent.setText("Tan");
        Tangent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TangentActionPerformed(evt);
            }
        });

        BackSpace.setText("DEL");
        BackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackSpaceActionPerformed(evt);
            }
        });

        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        openBracket.setText("(");
        openBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBracketActionPerformed(evt);
            }
        });

        closeBracket.setText(")");
        closeBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBracketActionPerformed(evt);
            }
        });

        Screen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Screen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(73, Short.MAX_VALUE)
                        .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(put0, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(put7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(put4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(put1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(put8, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(put2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(put5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(putDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(put9, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(put6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(put3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(openBracket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(closeBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cosine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tangent, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(put1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(put2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(put3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(put4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(put6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(put5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sine, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(put8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(put9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(put7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cosine, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(put0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(putDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tangent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void put1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put1ActionPerformed
        eqn.add(1);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put1ActionPerformed

    private void put2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put2ActionPerformed
        eqn.add(2);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put2ActionPerformed

    private void put5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put5ActionPerformed
        eqn.add(5);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put5ActionPerformed

    private void put3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put3ActionPerformed
        eqn.add(3);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put3ActionPerformed

    private void put4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put4ActionPerformed
        eqn.add(4);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put4ActionPerformed

    private void put6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put6ActionPerformed
        eqn.add(6);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put6ActionPerformed

    private void put7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put7ActionPerformed
        eqn.add(7);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put7ActionPerformed

    private void put8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put8ActionPerformed
        eqn.add(8);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put8ActionPerformed

    private void put9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put9ActionPerformed
        eqn.add(9);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put9ActionPerformed

    private void put0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_put0ActionPerformed
        eqn.add(0);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_put0ActionPerformed

    private void putDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putDecimalActionPerformed
        eqn.add('.');
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_putDecimalActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        eqn.add('+');
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_addActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        eqn.add('-');
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_subActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        eqn.add('*');
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_mulActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        eqn.add('/');
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_divActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        ScriptEngineManager mg = new ScriptEngineManager();
        ScriptEngine engine = mg.getEngineByName("JavaScript");
        String infix = Screen.getText();
        try {
            double d = (double) engine.eval(infix);
            String s = Double.toString(d);
            char[] c = s.toCharArray();
            eqn = new ArrayList<>();
            for (int i = 0; i < c.length; i++) {
                eqn.add(c[i]);
            }

            Screen.setText(s);

        } catch (Exception ex) {
            Screen.setText("Math Error");
            Logger.getLogger(Calculator2.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_equalsActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        eqn = new ArrayList<>();
        Screen.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void BackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackSpaceActionPerformed
        eqn.remove(eqn.size() - 1);
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_BackSpaceActionPerformed

    private void SineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SineActionPerformed
        eqn.add("Math.sin(");
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_SineActionPerformed

    private void openBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBracketActionPerformed
        eqn.add('(');
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_openBracketActionPerformed

    private void closeBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBracketActionPerformed
        eqn.add(')');
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_closeBracketActionPerformed

    private void CosineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosineActionPerformed
        eqn.add("Math.cos(");
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_CosineActionPerformed

    private void TangentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TangentActionPerformed
        eqn.add("Math.tan(");
        String s = "";
        Iterator<Object> itr = eqn.iterator();
        while (itr.hasNext()) {
            s = s + itr.next();
        }
        Screen.setText(s);
    }//GEN-LAST:event_TangentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator2().setVisible(true);
            }
        });
    }
    ArrayList<Object> eqn = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackSpace;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Cosine;
    private javax.swing.JLabel Screen;
    private javax.swing.JButton Sine;
    private javax.swing.JButton Tangent;
    private javax.swing.JButton add;
    private javax.swing.JButton closeBracket;
    private javax.swing.JButton div;
    private javax.swing.JButton equals;
    private javax.swing.JButton mul;
    private javax.swing.JButton openBracket;
    private javax.swing.JButton put0;
    private javax.swing.JButton put1;
    private javax.swing.JButton put2;
    private javax.swing.JButton put3;
    private javax.swing.JButton put4;
    private javax.swing.JButton put5;
    private javax.swing.JButton put6;
    private javax.swing.JButton put7;
    private javax.swing.JButton put8;
    private javax.swing.JButton put9;
    private javax.swing.JButton putDecimal;
    private javax.swing.JButton sub;
    // End of variables declaration//GEN-END:variables
}
